test-blog4:
  stage: test
  script:
    - cd project
    # vvv Temporarily shut it down vvv
    # - bundle install
    # - rails db:migrate RAILS_ENV=test
    # - PARALLEL_WORKERS=1 rails test
  only:
    - project

deploy-blog4:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./project /
    - cd /project
    - bundle install
    - rails db:migrate
	- rails db:seed  # Useful if I changed the db/seeds.rb
    - sv restart project
  only:
    - project
